runs:
  using: composite
  steps:
    - name: Install PowerShell.MCP from PS Gallery
      shell: pwsh
      run: |
        Install-PSResource -Name 'PowerShell.MCP' -Scope CurrentUser -TrustRepository
        $proxy = Get-ChildItem -Path ($env:PSModulePath -split ':') -Filter 'PowerShell.MCP.Proxy' -Recurse -ErrorAction SilentlyContinue |
          Where-Object { $_.FullName -match 'linux-x64' } |
          Select-Object -First 1 -ExpandProperty FullName
        chmod +x $proxy
        New-Item -ItemType SymbolicLink -Path '/usr/local/bin/PowerShell.MCP.Proxy' -Target $proxy -Force
